# Generated by Django 5.2.15 on 2026-06-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120, verbose_name='企业名称')),
                ('name', models.CharField(max_length=80, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='电话')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='产品品类')),
                ('sku', models.CharField(blank=True, max_length=80, verbose_name='SKU 数量')),
                ('timeline', models.DateField(blank=True, null=True, verbose_name='交付时间')),
                ('asset_type', models.CharField(blank=True, max_length=40, verbose_name='需要内容')),
                ('budget', models.CharField(blank=True, max_length=40, verbose_name='预算范围')),
                ('platform', models.CharField(blank=True, max_length=120, verbose_name='目标平台')),
                ('note', models.TextField(blank=True, verbose_name='产品图与品牌资料说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '联系表单',
                'verbose_name_plural': '联系表单',
                'db_table': 'contract',
                'ordering': ['-created_at'],
            },
        ),
    ]
